filebrowser/urls.py
# As of version 3.4, all urls moved to FileBrowserSite class in filebrowser.sites

src/main/urls.py
from django.conf.urls import patterns, url, include
from src.main.models import StaticPage

urlpatterns = patterns('src.main.views',
    url(r'^$', 'index', name='index'),
    url(r'^news/$', 'news', name='news'),
    url(r'^news/(?P<pk>\d+)/$', 'news_detail', name='news_detail'),
)

for page in StaticPage.objects.all():
    urlpatterns += patterns('src.main.views',
        url(r'%s' % page.url, 'staticpage', {'content': page.content}, name='staticpage')
    )

src/shop/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

urlpatterns = patterns('src.shop.views',
    # Главная страница
    url(r'^$', 'index_view', name='catalog_home'),
    # Просмотр категории
    url(r'^category/(?P<category_slug>[-\w]+)/$', 'category_view', name='catalog_category'),
    # Просмотр товара
    url(r'^product/(?P<product_slug>[-\w]+)/$', 'product_view', name='catalog_product'),
)

src/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('src.main.urls')),
    url(r'^service/', include('src.services.urls')),
    url(r'^shop/', include('src.shop.urls')),
    # Страница обработки товара при добавлении в корзину
    url(r'^buy/(?P<product_slug>[-\w]+)/$', 'src.shop.views.buy'),
    # Просмотр корзины с товарами и услугами
    url(r'cart/', 'src.shop.views.cart_view'),
)


if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),)
    urlpatterns += staticfiles_urlpatterns()


from filebrowser.sites import site
urlpatterns += patterns('',
                        url(r'^admin/filebrowser/', include(site.urls)),
                        )

src/main/models.py
    # -*- coding: utf-8 -*-

from django.db import models


class News(models.Model):
    title = models.CharField(max_length=255, verbose_name=u'Заголовок')
    description = models.TextField(blank=True, verbose_name=u'Краткое описание')
    content = models.TextField(blank=True, verbose_name=u'Содержимое')
    created_at = models.DateField(auto_now_add=True, verbose_name=u'Дата создания')

    class Meta:
        verbose_name = u'Новость'
        verbose_name_plural = u'Новости'

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return '/news/%s/' % self.pk

class StaticPage(models.Model):
    title = models.CharField(verbose_name=u'Заголовок', max_length=250)
    url = models.CharField(verbose_name=u'Ссылка', max_length=250)
    content = models.TextField(verbose_name=u'Содержимое')

    class Meta:
        verbose_name = u'Статическая страница'
        verbose_name_plural = u'Статические страницы'

    def __unicode__(self):
        return self.title

src/services/avia/models.py
from django.db import models

# Create your models here.

src/services/models.py
# -*- coding: utf-8 -*-

from django.db import models

class State(models.Model):
    title = models.CharField(verbose_name=u'Страна/Регион', max_length=250)

    class Meta:
        verbose_name = u'Страна'
        verbose_name_plural = u'Страны'
        ordering=['title',]

    def __unicode__(self):
        return self.title


class City(models.Model):
    state = models.ForeignKey(State, verbose_name=u'Страна')
    title = models.CharField(verbose_name=u'Город', max_length=250)

    class Meta:
        verbose_name = u'Город'
        verbose_name_plural = u'Города'
        ordering=['title',]

    def __unicode__(self):
        return self.title

src/shop/models.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.db import models
from django.db.models import permalink
from mptt.models import MPTTModel, TreeForeignKey
from filebrowser.fields import FileBrowseField


class Category(MPTTModel):
    """Класс для категорий товаров"""
    name = models.CharField(u'Название', max_length=50, unique=True)
    slug = models.SlugField(u'Ссылка', max_length=50, unique=True,
                            help_text=u'Ссылка формируется из названия')
    # "Чистые" ссылки для продуктов формирующиеся из названия
    description = models.TextField(u'Описание')
    meta_keywords = models.CharField(u'Ключевые слова', max_length=255,
                                     help_text=u'Через запятую')
    # Разделенные запятыми теги для SEO оптимизации
    meta_description = models.CharField(u'Краткое описание', max_length=255,
                                        help_text=u'Используется для поисквой оптимизации')
    created_at = models.DateTimeField(u'Дата создание', auto_now_add=True)
    updated_at = models.DateTimeField(u'Дата обновления', auto_now=True)
    parent = TreeForeignKey('self', verbose_name=u'Родительская категория',
                            related_name='children', blank=True,
                            help_text=u'Родитлеьская категория для данной категории', null=True)

    class Meta:
        db_table = 'categories'
        ordering = ['-created_at']
        verbose_name_plural = u'Категории'

    def __unicode__(self):
        return self.name

    @permalink
    def get_absolute_url(self):
        """Генерация постоянных ссылок на категории"""
        return ('catalog_category', (), {'category_slug': self.slug})



class FeaturedProductManager(models.Manager):
    """Класс менеджер для вывода продвигаемых продуктов"""
    def get_query_set(self):
        return super(FeaturedProductManager, self).get_query_set().filter(is_featured=True)


class Product(models.Model):
    """Класс для товаров"""
    name = models.CharField(u'Название', max_length=255, unique=True)
    slug = models.SlugField(u'Ссылка', max_length=255, unique=True,
                            help_text=u'Уникальное значение для каждого товара. Формируется из названия.')
    brand = models.CharField(u'Производитель', max_length=50, blank=True)
    price = models.DecimalField(verbose_name=u'Стимость единицы товара', max_digits=9, decimal_places=2)
    old_price = models.DecimalField(max_digits=9, decimal_places=2,
                                    blank=True, default=0.00)
    is_featured = models.BooleanField(u'Отображать на главной', default=False) # Отображать на главной
    quantity = models.IntegerField(u'Quantity')
    description = models.TextField(u'Описание')
    meta_keywords = models.CharField(u'Ключевые слова', max_length=255,
                                     help_text=u'Через запятую')
    meta_description = models.CharField(u'Краткое описание', max_length=255,
                                        help_text=u'Используется для поисковой оптимизации')
    created_at = models.DateTimeField(u'Дата добавления', auto_now_add=True)
    updated_at = models.DateTimeField(u'Дата обновления', auto_now=True)
    #!buy_count = models.IntegerField(u'Количество продаж', default=0)
    categories = models.ManyToManyField(Category, verbose_name=u'Категории',
                                        help_text=u'Категории, к которым принадлежит продукт')

    objects = models.Manager()
    feautured = FeaturedProductManager()
    class Meta:
        db_table = 'products'
        ordering = ['-created_at']
        verbose_name_plural = u'Товары'

    def __unicode__(self):
        return self.name

    @permalink
    def get_absolute_url(self):
        """Генерация постоянных ссылок на товары"""
        return ('catalog_product', (), {'product_slug': self.slug})

    @property
    def sale_price(self):
        """
        Метод возвращает старую цену товара
        будет использоваться в шаблонах для отображения
        старой цены под текущей
        """
        if self.old_price > self.price:
            return True
        else:
            return False


class ProductImage(models.Model):
    """Изображения продуктов"""
    product = models.ForeignKey(Product, verbose_name=u'Товар')
    image = FileBrowseField(directory=u'ProductPhotos/', verbose_name=u'Фото', max_length=250, blank=True, null=True)
    description = models.CharField(verbose_name=u'Подпись', max_length=250, blank=True)
    default = models.BooleanField(u'Главное фото', default=False)

    class Meta:
        db_table = 'product_images'

src/services/hotels/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import HotelOrder


class HotelOrderForm(forms.ModelForm):

    class Meta:
        model = HotelOrder
        fields = ('email', 'phone', 'city', 'title', 'starcount', 'date_on', 'date_off', 'people_count', 'content')

src/shop/forms.py
# -*- coding: utf-8 -*-

from django import forms
from src.shop.cart.models import Client

class OrderForm(forms.ModelForm):

    class Meta:
        model = Client
        fields = ('name', 'email', 'phone', 'other')

src/main/views.py
# -*- coding: utf-8 -*-

from django.views.generic import DetailView, ListView
from src.main.models import News
from src.decorators import  render_to

class NewsDetail(DetailView):
    model = News

news_detail = NewsDetail.as_view()

class NewsList(ListView):
    model = News
    paginate_by = 10

news = NewsList.as_view()


@render_to('main/index.html')
def index(request):
    return {}


@render_to('main/static_page.html')
def staticpage(request, content):
    return {'content': content}

src/services/avia/views.py
# -*- coding: utf-8 -*-

from src.decorators import render_to

@render_to('services/avia/index.html')
def index(request):
    return {}

src/services/hotels/views.py
# -*- coding: utf-8 -*-

from django.http import Http404, HttpResponseRedirect
from django.contrib import messages

from src.decorators import render_to
from .models import Hotel, HotelRoom
from src.services.models import City
from .forms import HotelOrderForm


import django_filters
from django_filters.widgets import LinkWidget

class HotelRoomFilter(django_filters.FilterSet):
    price = django_filters.RangeFilter(label=u'Стоимость')
    hotel__starcount = django_filters.AllValuesFilter(label=u'Количество звезд', widget=LinkWidget)
    class Meta:
        model = HotelRoom
        fields = ['price','hotel__city','hotel__title','hotel__starcount']

    def __init__(self, *args, **kwargs):
        super(HotelRoomFilter, self).__init__(*args, **kwargs)
        self.filters['hotel__city'].extra.update({'empty_label': u'Любой'})


def m_cl(k, req):
    if (k in req.GET.keys()) and (req.GET[k]):
        return True
    else:
        return False


@render_to('services/hotels/index.html')
def index(request):
    roomf = HotelRoomFilter(request.GET, queryset=HotelRoom.objects.all())
    hotels = []
    for room in roomf:
        if not room.hotel in hotels:
            hotels.append(room.hotel)

    titles = u'Гостиницы'
    if m_cl('hotel__title', request):
        titles += u' c названием <span>'+request.GET['hotel__title']+u'</span>'
    if m_cl('hotel__starcount', request):
        count = request.GET['hotel__starcount']
        if count=='1':
            titles += u' <span>1 звезда</span>'
        elif count=='0' or count==5:
            titles += u' <span>'+count+u' звезд</span>'
        elif count in ['2','3','4']:
            titles += u' <span>'+count+u' звезды</span>'
    if m_cl('hotel__city', request):
        try:
            city = City.objects.get(pk=request.GET['hotel__city'])
            titles += u' в городе <span>' + city.title + u'</span>'
        except:
            pass
    if m_cl('price_0',request) and m_cl('price_1',request):
        titles += u' с ценой от <span>'+request.GET['price_0'] + u'</span> до <span>' + request.GET['price_1'] + u'</span> р. за ночь'

    if request.method == 'POST':
        form = HotelOrderForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, u'Спасибо за Ваш заказ.')
            return HttpResponseRedirect(request.path)
        else:
            messages.error(request, u'Пожалуйста, исправьте ошибки и отправьте форму еще раз')
    form = HotelOrderForm()
    return {'room_filter': roomf, 'hotels': hotels, 'titles': titles, 'form': form}


@render_to('services/hotels/hotel_view.html')
def hotel_view(request, hotel_pk):
    try:
        hotel = Hotel.objects.get(pk=hotel_pk)
    except:
        raise Http404

    return {'hotel': hotel,}

src/services/views.py
# -*- coding: utf-8 -*-

from src.decorators import render_to

@render_to('services/index.html')
def index(request):
    return {}

src/shop/cart/views.py
# -*- coding: utf-8 -*-

src/shop/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.http import Http404, HttpResponseRedirect

from src.decorators import render_to
from .models import Product, Category
from src.services.hotels.models import HotelRoom
from src.shop.cart.models import CartItem

from cart import cart


@render_to('shop/index.html')
def index_view(request):
    sales = []
    for product in Product.objects.all():
        if product.sale_price:
            sales.append(product)
    other = Product.feautured.all()
    return {'sales': sales, 'other': other}


def create_road(cat):
    import copy
    node_list = []
    node_list.append(cat)
    parent = cat.parent
    while parent:
        node_list.append(copy.deepcopy(parent))
        parent = parent.parent
    road = u'<a href="/shop/">Магазин</a>'
    for nod in reversed(node_list):
        road += u' > <a href="/shop/category/%s/">%s</a>' % (unicode(nod.slug), unicode(nod.name))
    return road


@render_to('shop/category_view.html')
def category_view(request, category_slug):
    c = get_object_or_404(Category.objects, slug = category_slug) #Берем категорию
    ch = c.get_descendants() # ВСЕ дочерние категории
    child = [i for i in ch if i.parent.name == c.name] #Только те дочерние категории, родитель которых - данная категория
    products = c.product_set.all()
    return {'category': c, 'children_cat': child, 'products': products, 'road': create_road(c)}


@render_to('shop/product_view.html')
def product_view(request, product_slug):
    product = get_object_or_404(Product.objects, slug = product_slug)
    return {'product': product, 'road': create_road(product.categories.all()[0])}


@render_to('shop/buy.html')
def buy(request, product_slug):
    if request.method == 'POST':
        if Product.objects.filter(slug=product_slug):
            cart.product_add_to_cart(request)
        elif HotelRoom.objects.filter(slug=product_slug):
            cart.hotel_add_to_cart(request)
        messages.success(request, u'Заказ добавлен в корзину')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        raise Http404


from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render_to_response
from django.template import RequestContext
from .forms import OrderForm
from cart.models import Client
@csrf_protect
def cart_view(request):
    """Представление для отображения корзины"""
    page_title = u'Просмотр корзины'
    if request.method == 'POST':
        postdata = request.POST.copy()
        if postdata.has_key('remove'):
            cart.remove_from_cart(request)
        if postdata.has_key('update'):
            cart.update_cart(request)
        if postdata.has_key('checkout'):
            form = OrderForm(request.POST)
            if form.is_valid():
                tmpcart = CartItem.objects.get(cart_id=cart.get_cart_id(request))
                cl = Client(name=request.POST['name'], email=request.POST['email'], phone=request.POST['phone'], other=request.POST['other'])
                cl.cart = tmpcart
                cl.save()
                tmpcart.order = True
                tmpcart.save()
                messages.success(request,u'Спасибо за Ваш заказ. Мы свяжемся с Вами в ближайшее время.')
                cart.empty_cart(request)
                return HttpResponseRedirect('/')
            else:
                messages.error(request, u'Неверно введенные данные.')
    form = OrderForm()
    cart_items = cart.get_cart_items(request)
    products = cart_items['products']
    hotels = cart_items['hotels']
    cart_subtotal = cart.cart_subtotal(request)
    return render_to_response('shop/cart.html', locals(),
                              context_instance=RequestContext(request))

src/templates/shop/base_shop.html
{% extends 'base.html' %}
{% load catalog_tags %}



{% block content %}
    <div class="row-fluid">
        <div class="span3">
            {% block left_col %}
                {% categories_tree %}
                <br>
                <div class="cart_prev">
                    {% if cart_item_count %}
                        В корзине <a href="/cart/" class="carta">
                        {% if cart_item_count == 1 %}
                            1 товар
                        {% elif cart_item_count == 2 or cart_item_count == 3 or cart_item_count == 4 %}
                            {{ cart_item_count }} товара
                        {% else %}
                            {{ cart_item_count }} товаров
                        {% endif %}
                        </a>
                        <a href="/cart/" class="label label-success pull-right">Оформить</a><div class="clear"></div>
                    {% else %}
                        Ваша корзина пуста
                    {% endif %}
                </div>
            {% endblock %}
        </div>
        <div class="span9">
            <div class="row-fluid">
                <div class="span12">
                    <span class="muted road">{% block road_link %}<a href="/shop/">Магазин</a>{% endblock %}</span>
                </div>
            </div>
            {% block center_col %}{% endblock %}
        </div>
    </div>
{% endblock %}

src/templates/shop/buy.html
{% extends 'base.html' %}

{% block title %}Заносим товар в корзину{% endblock %}

{% block content %}
    111
{% endblock %}

src/templates/shop/cart.html
{% extends 'shop/base_shop.html' %}

{% block title %}{{ page_title }}{% endblock %}

{% block center_col %}
    <table class="table">
        <caption>Ваш заказ</caption>
        <thead>
        <tr>
            <th scope="col">Товар</th>
            <th scope="col">Стоимость</th>
            <th>Количество</th>
            <th></th>
            <th></th>
            <th scope="col" class="right">Всего</th>
        </tr>
        </thead>
        <tbody>
        {% if cart_item_count %}
            {% for item in cart_items.hotels %}
                <tr>
                    <td>
                        <a href="{{ item.get_absolute_url }}" class="cart">
                            {{ item.name }}
                        </a><br>
                        <a href="{{ item. }}"
                    </td>
                    <td>
                        {{ item.price }} руб.
                    </td>
                    <td class="right">
                        <form method="post" action="." class="cart">{% csrf_token %}
                            {#<label class="control-label" for="quantity">{% trans "Quantity" %}:</label>#}
                            <input type="text" name="quantity" value="{{ item.quantity }}" id="quantity"
                                   size="2" class="quantity" maxlength="5" />
                            <input type="hidden" name="product_slug" value="{{ item.product.slug }}" />
                    </td>
                    <td>
                        <input type="hidden" name="product_slug" value="{{ item.product.slug }}" />
                        <button class="btn btn-info" type="submit" name="update">
                            <i class="icon-refresh icon-white"></i> Обновить</button>
                        </form>
                    </td>
                    <td>
                        <form method="post" action="." class="cart">{% csrf_token %}
                            <input type="hidden" name="product_slug" value="{{ item.product.slug }}" />
                            <button class="btn btn-danger" type="submit" name="remove">
                                <i class="icon-trash icon-white"></i> Удалить</button>
                        </form>
                    </td>
                    <td class="right">{{ item.total }} руб.</td>
                </tr>
            {% endfor %}
            {% for item in cart_items.products %}
                <tr>
                    <td>
                        <a href="{{ item.get_absolute_url }}" class="cart">
                            {{ item.name }}
                        </a>
                    </td>
                    <td>
                        {{ item.price }} руб.
                    </td>
                    <td class="right">
                        <form method="post" action="." class="cart">{% csrf_token %}
                            <input type="text" name="quantity" value="{{ item.quantity }}" id="quantity"
                                   size="2" class="quantity" maxlength="5" />
                            <input type="hidden" name="product_slug" value="{{ item.product.slug }}" />
                    </td>
                    <td>
                        <input type="hidden" name="product_slug" value="{{ item.product.slug }}" />
                        <button class="btn btn-info" type="submit" name="update">
                            <i class="icon-refresh icon-white"></i> Обновить</button>
                        </form>
                    </td>
                    <td>
                        <form method="post" action="." class="cart">{% csrf_token %}
                            <input type="hidden" name="product_slug" value="{{ item.product.slug }}" />
                            <button class="btn btn-danger" type="submit" name="remove">
                                <i class="icon-trash icon-white"></i> Удалить</button>
                        </form>
                    </td>
                    <td class="right">{{ item.total }} руб.</td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="6" style="height:30px;">
                    Ваша корзина пуста
                </td>
            </tr>
        {% endif %}
        </tbody>
        <tfoot>
        <tr>
            <th colspan="5">Полная стоимость:</th>
            <th>{{ cart_subtotal }} руб.</th>
        </tr>
        </tfoot>
    </table>
    {% if cart_item_count %}
        <br><br>
        {% load bootstrap %}
        <div class="row-fluid">
            <div class="span12">
                <h4>Оформить заказ</h4>
                <hr>
                <form method="post" action="." class="form-horizontal">{% csrf_token %}
                    {{ form|bootstrap }}
                    <button class="btn btn-success" type="submit" name="checkout">Отправить</button>
                </form>
            </div>
        </div>
    {% endif %}
{% endblock %}

src/templates/shop/category_view.html
{% extends 'shop/base_shop.html' %}
{% load catalog_tags %}

{% block title %}{{ category.name }}{% endblock %}

{% block road_link %}{{ road|safe }}{% endblock %}

{% block center_col %}
    <div class="category_head">
        <h3>{{ category.name }}</h3>
        <div class="description">{{ category.description }}</div>
    </div>
    {% for child in children_cat %}
        {% products_block child.name child.product_set.all|slice:":3" child.slug %}
    {% endfor %}
    {% products_block '' category.product_set.all '' %}
{% endblock %}

src/templates/shop/index.html
{% extends 'shop/base_shop.html' %}
{% load catalog_tags %}

{% block center_col %}
    {% if sales %}{% products_block 'Товары со скидкой' sales '' %}{% endif %}
    {% products_block '' other '' %}
{% endblock %}

src/templates/shop/product_view.html
{% extends 'shop/base_shop.html' %}
{% load catalog_filter %}

{% block title %}{{ product.name }}{% endblock %}

{% block road_link %}{{ road|safe }}{% endblock %}

{% block center_col %}
    <script type="text/javascript">
        jQuery(document).ready(function() {
            jQuery("a.thumbnail").fancybox(
                    {
                        'titlePosition'	:	'over',
                        'onComplete'	:	function() {
                            jQuery("#fancybox-wrap").hover(function() {
                                        jQuery("#fancybox-title").show();
                                    },
                                    function() {jQuery("#fancybox-title").hide();});
                        }
                    }
            );
            jQuery('#orders').fancybox();
        });
    </script>
    <div class="row-fluid">
        <div class="span8 offset2 category_head">
            <h3 style="text-align: center">{{ product.name }}</h3>
            <div class="row-fluid">

{#                Картинки#}
                <div class="span4">
                    <div class="row-fluid">
                        <ul class="thumbnails">
                            <li class="span12">
                                <a rel="product{{ product.pk }}" href="{{ MEDIA_URL }}{{ product|default_image }}" class="thumbnail" title="{{ product.name }}">
                                    <img src="{{ MEDIA_URL }}{{ product|default_image }}" title="{{ product.name }}">
                                </a>
                            </li>
                            {% for photo in product.productimage_set.all %}
                                <li class="span3">
                                    <a rel="product{{ product.pk }}" href="{{ MEDIA_URL }}{{ photo.image }}" class="thumbnail" title="{{ photo.description }}">
                                        <img src="{{ MEDIA_URL }}{{ photo.image }}" title="{{ photo.description }}" style="height: 40px">
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

{#                Описание#}
                <div class="span8">
                    <p>Производитель: <strong>{{ product.brand }}</strong></p>
                    <p>Цена:
                        {% if product.sale_price %}<span class="old_price">{{ product.old_price }} р.</span> {% endif %}
                        <span class="price">{{ product.price }} р.</span>
                    </p>
                    {{ product.description|safe }}
                    <br><br>
                    <form method="post" action="/buy/{{ product.slug }}/">{% csrf_token %}
                        <input type="hidden" name="product_slug" value="{{ product.slug }}" />
                        <input class="buy" type="submit" value="Купить"
                               name="submit" alt="Добавить в корзину" />
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}